# ============================================================
# base.yaml — universal defaults + RISC-V format templates
# ============================================================

meta:
  version: 0
  notes: "Shared anchors for ISAs. Extend per-family as needed."

defaults: &defaults
  endianness: little
  register_count: 32
  default_pc: 0x80000000
  # mutation hints are optional; your mutator can ignore if unknown
  mutation_hints:
    reg_prefers_zero_one_hot: true
    signed_immediates_bias: true
    align_load_store: 4

# RISC-V 32/64 common instruction formats (LSB0 bit numbering)
riscv_formats: &riscv_formats
  R:
    fields:
      - {name: opcode, bits: [0,6]}
      - {name: rd,     bits: [7,11]}
      - {name: funct3, bits: [12,14]}
      - {name: rs1,    bits: [15,19]}
      - {name: rs2,    bits: [20,24]}
      - {name: funct7, bits: [25,31]}
  I:
    fields:
      - {name: opcode, bits: [0,6]}
      - {name: rd,     bits: [7,11]}
      - {name: funct3, bits: [12,14]}
      - {name: rs1,    bits: [15,19]}
      - {name: imm,    bits: [20,31], signed: true}
  S:
    fields:
      - {name: opcode, bits: [0,6]}
      - {name: imm0,   bits: [7,11]}
      - {name: funct3, bits: [12,14]}
      - {name: rs1,    bits: [15,19]}
      - {name: rs2,    bits: [20,24]}
      - {name: imm1,   bits: [25,31]}
  B:
    fields:
      - {name: opcode, bits: [0,6]}
      - {name: imm0,   bits: [7,7]}
      - {name: imm1,   bits: [8,11]}
      - {name: funct3, bits: [12,14]}
      - {name: rs1,    bits: [15,19]}
      - {name: rs2,    bits: [20,24]}
      - {name: imm2,   bits: [25,30]}
      - {name: imm3,   bits: [31,31]}
  U:
    fields:
      - {name: opcode, bits: [0,6]}
      - {name: rd,     bits: [7,11]}
      - {name: imm,    bits: [12,31]}
  J:
    fields:
      - {name: opcode, bits: [0,6]}
      - {name: rd,     bits: [7,11]}
      - {name: imm,    bits: [12,31]}

# Optional compressed 16-bit template (simplified; you’ll refine later)
riscv_c_formats: &riscv_c_formats
  C16:
    fields:
      - {name: opcode, bits: [0,1]}
      - {name: funct3, bits: [13,15]}
      - {name: body,   bits: [2,12]}

common_rules: &common_rules
  <<: *defaults
  compare_oracle:
    # Architectural state to compare by default
    regs: true
    fp_regs: false
    pc: true
    memory_touchset_hash: true
    csrs_whitelist: []     # fill in per core if needed
    csrs_blacklist: [mcycle, minstret]  # non-deterministic counters